package Application;

import com.formdev.flatlaf.FlatClientProperties;
import com.formdev.flatlaf.FlatDarkLaf;
import com.formdev.flatlaf.FlatLightLaf;
import com.formdev.flatlaf.themes.FlatMacDarkLaf;
import java.awt.Color;
import java.awt.Toolkit;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.SwingUtilities;
import javax.swing.UIManager;


public class Main extends javax.swing.JFrame {
    String id;
    
      public Main() {
        
        initComponents();
      }

    public Main(String id, String name, String status) {
        
        initComponents();
        
        this.setTitle("ຜູ້ໃຊ້ງານ:" + name);
        
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        //ໃສຮູບ icon ໂປຣແກຣມ
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("../image/logo.png")));
        //ປຽນສີແຖບ Title bar ດ້ານເທິງ
        getRootPane().putClientProperty(FlatClientProperties.TITLE_BAR_BACKGROUND, new Color(220, 220, 220));
        //ICON ໃນແຖບ Titlr bar ບໍ່ໃຫ້ສະແດງ
        getRootPane().putClientProperty(FlatClientProperties.TITLE_BAR_BACKGROUND, false);

        //ເມື່່ອກົດປິດທີ່ເຄື່ອງໝາຍXທີ່ຟອມບໍ່ໃຫ້ມັນທຳງານຫຼັງຈາກນັ້ນຈຶ້ງໄປສ້າງ EventWindowClosingເພື່ອປິດ
        this.setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);

        //ສີພື້ນຫຼັງໃຫ້ຕິກ ເລືອກທີ່ Flatlaf Light ກ່ອນ
        jCheckBoxMenuItem1Light.setSelected(true);
        //ເມື່ອຣັນມາໃຫ້ເອົາຫນ້າ PanelHome ມາສະແດງທີ່ PanelMain ກ່ອນ
        showPanel(new PanelHome(id));
        
        //ຖ້າສະຖານະພະນັກງານ ບໍ່ເທົ່າກັບ admin ຈະບໍ່ໃຫ້ເຂົ້າ ຈັດການຂໍ້ມູນ,ສັ່ງຊື້-ນຳເຂົ້າ ແລະ ລາຍງານ
        if(!status.equals("Admin")){
            jMenuData.setVisible(false);
            jMenuOrder.setVisible(false);
            jMenuReport.setVisible(false);
        }
    }
    //ສ້າງເມັດສີເພື່ອສະຫຼັບຫນ້າມ່ສະແດງທີ່PanelMain
    private void showPanel(JPanel panel) {
        PanelMain.removeAll();
        PanelMain.add(panel);
        PanelMain.validate();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        PanelMain = new javax.swing.JPanel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuHome = new javax.swing.JMenu();
        jMenuData = new javax.swing.JMenu();
        jMenuItemEmployee = new javax.swing.JMenuItem();
        jMenuItem7 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuOrder = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        jMenuItem9 = new javax.swing.JMenuItem();
        jMenuCutomer = new javax.swing.JMenu();
        jMenu18 = new javax.swing.JMenu();
        jMenu19 = new javax.swing.JMenu();
        jMenuReport = new javax.swing.JMenu();
        jMenuItem10 = new javax.swing.JMenuItem();
        jMenuItem11 = new javax.swing.JMenuItem();
        jMenuItem12 = new javax.swing.JMenuItem();
        jMenuItem13 = new javax.swing.JMenuItem();
        jMenuItem14 = new javax.swing.JMenuItem();
        jMenuItem15 = new javax.swing.JMenuItem();
        jMenuItem16 = new javax.swing.JMenuItem();
        jMenuItem17 = new javax.swing.JMenuItem();
        jMenu21 = new javax.swing.JMenu();
        jMenu22 = new javax.swing.JMenu();
        jCheckBoxMenuItem1Light = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem2Dark = new javax.swing.JCheckBoxMenuItem();
        jCheckBoxMenuItem3 = new javax.swing.JCheckBoxMenuItem();
        jMenu23 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        PanelMain.setBackground(new java.awt.Color(153, 153, 153));
        PanelMain.setLayout(new java.awt.BorderLayout());

        jMenuHome.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/home_Page.png"))); // NOI18N
        jMenuHome.setText("ໜ້າຫຼັກ");
        jMenuHome.setFont(new java.awt.Font("Saysettha OT", 0, 14)); // NOI18N
        jMenuHome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuHome.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuHome.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jMenuHome.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuHomeMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuHome);

        jMenuData.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/add_Database.png"))); // NOI18N
        jMenuData.setText("ຈັດການຂໍ້ມູນ");
        jMenuData.setFont(new java.awt.Font("Saysettha OT", 0, 14)); // NOI18N
        jMenuData.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuData.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuData.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jMenuItemEmployee.setFont(new java.awt.Font("Saysettha OT", 0, 14)); // NOI18N
        jMenuItemEmployee.setText("ຈັດການຂໍ້ມູນພະນັກງານ");
        jMenuItemEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemEmployeeActionPerformed(evt);
            }
        });
        jMenuData.add(jMenuItemEmployee);

        jMenuItem7.setFont(new java.awt.Font("Saysettha OT", 0, 14)); // NOI18N
        jMenuItem7.setText("ຈັດການຂໍ້ມູນສິນຄ້າ");
        jMenuData.add(jMenuItem7);

        jMenuItem3.setFont(new java.awt.Font("Saysettha OT", 0, 14)); // NOI18N
        jMenuItem3.setText("ຈັດການຂໍ້ມູນປະເພດ");
        jMenuData.add(jMenuItem3);

        jMenuItem4.setFont(new java.awt.Font("Saysettha OT", 0, 14)); // NOI18N
        jMenuItem4.setText("ຈັດການຂໍ້ມູນຍີ່ຫໍ້");
        jMenuData.add(jMenuItem4);

        jMenuItem5.setFont(new java.awt.Font("Saysettha OT", 0, 14)); // NOI18N
        jMenuItem5.setText("ຈັດການຂໍ້ມູນອັດຕາແລກປ່ຽນ");
        jMenuData.add(jMenuItem5);

        jMenuItem6.setFont(new java.awt.Font("Saysettha OT", 0, 14)); // NOI18N
        jMenuItem6.setText("ຈັດການຂໍ້ມູນຜູ້ສະໜອງ");
        jMenuData.add(jMenuItem6);

        jMenuBar1.add(jMenuData);

        jMenuOrder.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/order_Import.png"))); // NOI18N
        jMenuOrder.setText("ສັ່ງຊື້-ນຳເຂົ້າ");
        jMenuOrder.setFont(new java.awt.Font("Saysettha OT", 0, 14)); // NOI18N
        jMenuOrder.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuOrder.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuOrder.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jMenuItem8.setFont(new java.awt.Font("Saysettha OT", 0, 14)); // NOI18N
        jMenuItem8.setText("ຈັດການຂໍ້ມູນສັ່ງຊື້ສິນຄ້າ");
        jMenuOrder.add(jMenuItem8);

        jMenuItem9.setFont(new java.awt.Font("Saysettha OT", 0, 14)); // NOI18N
        jMenuItem9.setText("ຈັດການຂໍ້ມູນນຳເຂົ້າສິນຄ້າ");
        jMenuOrder.add(jMenuItem9);

        jMenuBar1.add(jMenuOrder);

        jMenuCutomer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/customer.png"))); // NOI18N
        jMenuCutomer.setText("ລູກຄ້າ");
        jMenuCutomer.setFont(new java.awt.Font("Saysettha OT", 0, 14)); // NOI18N
        jMenuCutomer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuCutomer.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuCutomer.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jMenuCutomer.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuCutomerMouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenuCutomer);

        jMenu18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/sale_Product.png"))); // NOI18N
        jMenu18.setText("ຂາຍສິນຄ້າ");
        jMenu18.setFont(new java.awt.Font("Saysettha OT", 0, 14)); // NOI18N
        jMenu18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu18.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu18.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jMenuBar1.add(jMenu18);

        jMenu19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search_Property.png"))); // NOI18N
        jMenu19.setText("ຄົ້ນຫາ");
        jMenu19.setFont(new java.awt.Font("Saysettha OT", 0, 14)); // NOI18N
        jMenu19.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu19.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu19.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jMenuBar1.add(jMenu19);

        jMenuReport.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/report_Card.png"))); // NOI18N
        jMenuReport.setText("ລາຍງານ");
        jMenuReport.setFont(new java.awt.Font("Saysettha OT", 0, 14)); // NOI18N
        jMenuReport.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenuReport.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenuReport.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        jMenuItem10.setFont(new java.awt.Font("Saysettha OT", 0, 14)); // NOI18N
        jMenuItem10.setText("ລາຍງານຂໍ້ມູນການຂາຍ");
        jMenuReport.add(jMenuItem10);

        jMenuItem11.setFont(new java.awt.Font("Saysettha OT", 0, 14)); // NOI18N
        jMenuItem11.setText("ລາຍງານຂໍ້ມູນສິິນຄ້າໃນຮ້ານ");
        jMenuReport.add(jMenuItem11);

        jMenuItem12.setFont(new java.awt.Font("Saysettha OT", 0, 14)); // NOI18N
        jMenuItem12.setText("ລາຍງານຂໍ້ມູນສິນຄ້າໄກ້ຫມົດ");
        jMenuReport.add(jMenuItem12);

        jMenuItem13.setFont(new java.awt.Font("Saysettha OT", 0, 14)); // NOI18N
        jMenuItem13.setText("ໃບບິນ");
        jMenuReport.add(jMenuItem13);

        jMenuItem14.setFont(new java.awt.Font("Saysettha OT", 0, 14)); // NOI18N
        jMenuItem14.setText("ລາຍງານຂໍ້ມູນສັ່ງຊື້ສິນຄ້າ");
        jMenuReport.add(jMenuItem14);

        jMenuItem15.setFont(new java.awt.Font("Saysettha OT", 0, 14)); // NOI18N
        jMenuItem15.setText("ລາຍງານຂໍ້ມູນນຳເຂົ້າ");
        jMenuReport.add(jMenuItem15);

        jMenuItem16.setFont(new java.awt.Font("Saysettha OT", 0, 14)); // NOI18N
        jMenuItem16.setText("ລາຍງານຂໍ້ມູນລູກຄ້າ");
        jMenuReport.add(jMenuItem16);

        jMenuItem17.setFont(new java.awt.Font("Saysettha OT", 0, 14)); // NOI18N
        jMenuItem17.setText("ລາຍງານຂໍ້ມູນພະນັກງານ");
        jMenuReport.add(jMenuItem17);

        jMenuBar1.add(jMenuReport);

        jMenu21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/profile.png"))); // NOI18N
        jMenu21.setText("ໂປໄຟລ");
        jMenu21.setFont(new java.awt.Font("Saysettha OT", 0, 14)); // NOI18N
        jMenu21.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu21.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu21.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jMenuBar1.add(jMenu21);

        jMenu22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/change_Theme.png"))); // NOI18N
        jMenu22.setText("ສີພື້ນ");
        jMenu22.setFont(new java.awt.Font("Saysettha OT", 0, 14)); // NOI18N
        jMenu22.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu22.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu22.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);

        buttonGroup1.add(jCheckBoxMenuItem1Light);
        jCheckBoxMenuItem1Light.setFont(new java.awt.Font("Saysettha OT", 1, 14)); // NOI18N
        jCheckBoxMenuItem1Light.setSelected(true);
        jCheckBoxMenuItem1Light.setText("Flatlaf Light");
        jCheckBoxMenuItem1Light.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem1LightActionPerformed(evt);
            }
        });
        jMenu22.add(jCheckBoxMenuItem1Light);

        buttonGroup1.add(jCheckBoxMenuItem2Dark);
        jCheckBoxMenuItem2Dark.setFont(new java.awt.Font("Saysettha OT", 1, 14)); // NOI18N
        jCheckBoxMenuItem2Dark.setText("Flatlaf Dark");
        jCheckBoxMenuItem2Dark.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem2DarkActionPerformed(evt);
            }
        });
        jMenu22.add(jCheckBoxMenuItem2Dark);

        buttonGroup1.add(jCheckBoxMenuItem3);
        jCheckBoxMenuItem3.setFont(new java.awt.Font("Saysettha OT", 1, 14)); // NOI18N
        jCheckBoxMenuItem3.setText("Flatlaf MacDark");
        jCheckBoxMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBoxMenuItem3ActionPerformed(evt);
            }
        });
        jMenu22.add(jCheckBoxMenuItem3);

        jMenuBar1.add(jMenu22);

        jMenu23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/shutdown.png"))); // NOI18N
        jMenu23.setText("ອອກລະບົບ");
        jMenu23.setFont(new java.awt.Font("Saysettha OT", 0, 14)); // NOI18N
        jMenu23.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jMenu23.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jMenu23.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jMenu23.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu23MouseClicked(evt);
            }
        });
        jMenuBar1.add(jMenu23);
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelMain, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jCheckBoxMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem3ActionPerformed
        getRootPane().putClientProperty(FlatClientProperties.TITLE_BAR_BACKGROUND, new Color(28, 40, 51));
        getRootPane().putClientProperty(FlatClientProperties.TITLE_BAR_FOREGROUND, new Color(253, 254, 254));
        SwingUtilities.invokeLater(() -> {
            try {
                UIManager.setLookAndFeel(new FlatMacDarkLaf());
                SwingUtilities.updateComponentTreeUI(this);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, e);
            }
        });        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxMenuItem3ActionPerformed

    private void jCheckBoxMenuItem1LightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem1LightActionPerformed
        getRootPane().putClientProperty(FlatClientProperties.TITLE_BAR_BACKGROUND, new Color(204, 209, 209));
        getRootPane().putClientProperty(FlatClientProperties.TITLE_BAR_FOREGROUND, new Color(23, 32, 42));
        SwingUtilities.invokeLater(() -> {
            try {
                UIManager.setLookAndFeel(new FlatLightLaf());
                SwingUtilities.updateComponentTreeUI(this);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, e);
            }
        });        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxMenuItem1LightActionPerformed

    private void jCheckBoxMenuItem2DarkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBoxMenuItem2DarkActionPerformed
        getRootPane().putClientProperty(FlatClientProperties.TITLE_BAR_BACKGROUND, new Color(39, 55, 70));
        getRootPane().putClientProperty(FlatClientProperties.TITLE_BAR_FOREGROUND, new Color(253, 254, 254));
        SwingUtilities.invokeLater(() -> {
            try {
                UIManager.setLookAndFeel(new FlatDarkLaf());
                SwingUtilities.updateComponentTreeUI(this);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(rootPane, e);
            }
        });        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBoxMenuItem2DarkActionPerformed

    private void jMenu23MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu23MouseClicked

        //ກົດອອກລະບົບໃຫ້ກັບໄປຫນ້າເຂົ້າໃໍໍຊ້ລະບົບ (Login)
        int data = JOptionPane.showConfirmDialog(rootPane, "ທ່ານຕ້ອງການອອກຈາກລະບົບແທ້ ຫຼື ບໍ່?", "ຢືນຢັນ",
                JOptionPane.OK_CANCEL_OPTION, JOptionPane.QUESTION_MESSAGE);
        if (data != 0) {
            return;
        }
        Login log = new Login();
        log.setVisible(true);
        dispose();
    }//GEN-LAST:event_jMenu23MouseClicked

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing

    }//GEN-LAST:event_formWindowClosing

    private void jMenuHomeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuHomeMouseClicked
            showPanel(new PanelHome(id));       
    }//GEN-LAST:event_jMenuHomeMouseClicked

    private void jMenuItemEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemEmployeeActionPerformed
        //showPanel(new PanelEmployee());
    }//GEN-LAST:event_jMenuItemEmployeeActionPerformed

    private void jMenuCutomerMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuCutomerMouseClicked
        showPanel(new PanelCustomer(id));
    }//GEN-LAST:event_jMenuCutomerMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelMain;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1Light;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem2Dark;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem3;
    private javax.swing.JMenu jMenu18;
    private javax.swing.JMenu jMenu19;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu21;
    private javax.swing.JMenu jMenu22;
    private javax.swing.JMenu jMenu23;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuCutomer;
    private javax.swing.JMenu jMenuData;
    private javax.swing.JMenu jMenuHome;
    private javax.swing.JMenuItem jMenuItem10;
    private javax.swing.JMenuItem jMenuItem11;
    private javax.swing.JMenuItem jMenuItem12;
    private javax.swing.JMenuItem jMenuItem13;
    private javax.swing.JMenuItem jMenuItem14;
    private javax.swing.JMenuItem jMenuItem15;
    private javax.swing.JMenuItem jMenuItem16;
    private javax.swing.JMenuItem jMenuItem17;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    private javax.swing.JMenuItem jMenuItem8;
    private javax.swing.JMenuItem jMenuItem9;
    private javax.swing.JMenuItem jMenuItemEmployee;
    private javax.swing.JMenu jMenuOrder;
    private javax.swing.JMenu jMenuReport;
    // End of variables declaration//GEN-END:variables
}
